spring:
  h2:
    console:
      enabled: true
      path: /sprinkling

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./sprinkling
    username: sa
    password:

  redis:
    host: localhost
    port: 6379

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: info
    org:
      hibernate:
        sql: debug
        type: trace